sudo: required

language: bash

services:
  - docker

script:
  - export APP_IMAGE=db-extractor-common
  - docker -v
  - docker build -t $APP_IMAGE .
  - docker-compose run wait
  - docker-compose run dev composer ci
