sudo: required

language: bash

services:
  - docker

install:
  - source ./generate-ssh-keys.sh
  - docker-compose build tests
  - docker-compose build sshproxy

script:
  - docker-compose run --rm tests

notifications:
  email: false
  slack:
    secure: cH3So8r+13n3qI+Kmsk21MsfbRJMEurZq8u5C2TDrCxrX+BYaZWY6ijOBlAOtNyNcwAFtmlYpUub8HuNWUOM903mSJdtaRCvNhWn4uMV6k98tJoe5EoP6NAeEr0qUsBWrBfHxYCY+rfUczDF3NaQnD9YDUMsOt/8WPn0OA8sHcYZJqn6Gg/PdXWpuX62nHyQTLb9fU2B7OxkWdV7tGqMuvf1kZbjopfCqUVNada8VTs6yb7mZSrwYBNuNLo4K//5OXkgByefkIpF7sok6wBgQPrE/zaBAz7GP1ue7jlDilrU3cdmEIfvFB0Scj1MQ3A8dSkQQW98fw6XmYs1sPZEV0xIruvCLgF3VsBHLPot82OpMMc8qfvvh5x0+D1lFJmhOXsBJPER7+caIO2E+zDMDX/ZStQ6SpDKUXiE1BkckyYCKI0YgCCwcPUr7f30QL0zU1zawYO6Q9SnLGa86sC0+DqIvmcM18Fvw72DiDMAE3VdmppdjYHHyoAgUlTRara1rZhx+bcF/u33CXFQztqCqM60jGmOEdBwUs4/xjFrk2U7/WePnSvjEGn/5WE0EGdULtB3hCSXn9ZlscTixqeluqzG4WXDmQiYXnpHwXtm9hQryA9V+th+7QOEXSNDP33twf/PgiRpBxpIaDXzQrN02IDyjuVV3F1bcwW+tzoE8ps=
